name: build status
on: [pull_request]
jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - run: mvn --batch-mode --update-snapshots verify
    # Collect and upload build artifacts from module targets instead of a non-existent staging folder
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: maven-build
        path: |
          **/target/*.jar
          **/target/*.war
          **/target/surefire-reports/**/*.xml
          **/target/failsafe-reports/**/*.xml
        if-no-files-found: ignore
