name: CI-CD Pipeline

on:
  push:
    tags: # 表示在创建新的 tag 时触发
      - v*

env:
  IMAGE_TAG: ${{ github.ref_name }}
  IMAGE_ENV: ghcr.io
  IMAGE_REGISTRY: bantanger/achobeta

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: pull commit head^3
        uses: actions/checkout@v3

      - name: setup java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: checkout code
        uses: actions/checkout@v2

      - name: start build java project
        run: mvn clean install package -Dmaven.test.skip=true

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_ENV }}
          username: BanTanger # 使用仓库的拥有者名作为用户名
          password: ${{ secrets.GHCR_IO_TOKEN }} # 使用存储在 GitHub Secrets 中的 ghcr.io 的访问令牌

      - name: docker compose build and push
        uses: docker/build-push-action@v2
        with:
          context: ./polaris-app
          file: ./polaris-app/Dockerfile
          # 所需要的体系结构，可以在 Available platforms 步骤中获取所有的可用架构
          platforms: linux/amd64,linux/arm64/v8
          # 镜像推送时间
          push: ${{ github.event_name != 'pull_request' }}
          # 给清单打上多个标签
          tags: |
            ${{ env.IMAGE_ENV }}/${{ env.IMAGE_REGISTRY }}/polaris:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_ENV }}/${{ env.IMAGE_REGISTRY }}/polaris:latest
#        run:
#          # cd polaris-app
#          # sudo sh build.sh
#          docker build -t ${{ env.IMAGE_ENV }}/${{ env.IMAGE_REGISTRY }}/polaris:${{ env.IMAGE_TAG }} -f ./Dockerfile .